### ISSUE TITLE
maintenanceEvent order is reversed during conversion

### ISSUE THREAD

**Issue by alexduryee** [SAA-SDT/eac1-to-eac2-conversion#1]
I don't know if the order of maintenanceEvents are super relevant, but they're reversed when going from 1->2

**Comment by fordmadox** [comment]
This was intentional on my part since I prefer to have newest events listed first (but the sorting only happens if the option to add the transformation event is turned on).  I can add a parameter to the transformation to make this an option, though. 

See https://github.com/SAA-SDT/eac1-to-eac2-conversion/blob/dd679ff3ce58405a98eff34c213a3482845afd64/eac1-to-eac2.xsl#L312-L313

**Comment by kerstarno** [comment]
I think, it might be good to have this as an option. While I personally agree with having the most recent events at the top, I also know that this is one of those things that comes down to personal preference, at least in the context of working in the XML files directly. :-)

**Comment by fordmadox** [comment]
A parameter has been added (see https://github.com/SAA-SDT/eac1-to-eac2-conversion/blob/0428c11da8dda95732662699cefb721fa57331a5/eac1-to-eac2.xsl#L37-L38), so I'm closing the issue.
