### ISSUE TITLE
xlink namespaces vs. non-namespaced attributes

### ISSUE THREAD

**Issue by alexduryee** [SAA-SDT/eac1-to-eac2-conversion#2]
Should xlink:arcrole (in source) have the namespace prefix?  I don't recall what the details of the decision were on moving xlink into EAC vs. dropping the namespace.

**Comment by kerstarno** [comment]
Out of the group of XLink attributes only `@xlink:href`, `@xlink:title`, and `@xlink:role` are kept and will be converted to `@href`, `@linkTitle`, and `@linkRole`. Existing `xlink:actuate`, `@xlink:arcrole`, and `@xlink:show` attributes could be kept nonetheless due to having the inclusion of attributes from any namespace enabled in EAC-CPF 2.0. However, this in turn requires the namespace to be specified, and that's why you could see an `@xlink:arcrole` still in EAC-CPF 2.0.

**Comment by fordmadox** [comment]
Closing this issue, as already answered above.
